//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uniCovid.resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uniCovid.resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string bthDownload {
            get {
                return ResourceManager.GetString("bthDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DEFAULT.
        /// </summary>
        public static string bthSalir {
            get {
                return ResourceManager.GetString("bthSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string btnCrud {
            get {
                return ResourceManager.GetString("btnCrud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DEFAULT.
        /// </summary>
        public static string btnLista {
            get {
                return ResourceManager.GetString("btnLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string btnModify {
            get {
                return ResourceManager.GetString("btnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string headerFecha {
            get {
                return ResourceManager.GetString("headerFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string headerProvincia {
            get {
                return ResourceManager.GetString("headerProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string headerTestAlumn {
            get {
                return ResourceManager.GetString("headerTestAlumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string headerTestProf {
            get {
                return ResourceManager.GetString("headerTestProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a flags/image.jpeg.
        /// </summary>
        public static string imgFlag {
            get {
                return ResourceManager.GetString("imgFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uniCovid.json.
        /// </summary>
        public static string jsonFile {
            get {
                return ResourceManager.GetString("jsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string labelChange {
            get {
                return ResourceManager.GetString("labelChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string lblInf {
            get {
                return ResourceManager.GetString("lblInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string lblProvincia {
            get {
                return ResourceManager.GetString("lblProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string lblTestAl {
            get {
                return ResourceManager.GetString("lblTestAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string lblTestPr {
            get {
                return ResourceManager.GetString("lblTestPr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string lblTituloDetalle {
            get {
                return ResourceManager.GetString("lblTituloDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string lblTituloEditar {
            get {
                return ResourceManager.GetString("lblTituloEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string lblTituloNuevo {
            get {
                return ResourceManager.GetString("lblTituloNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string ttCrear {
            get {
                return ResourceManager.GetString("ttCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a default.
        /// </summary>
        public static string ttLista {
            get {
                return ResourceManager.GetString("ttLista", resourceCulture);
            }
        }
    }
}
